name: linux-229-cli

on: [push, pull_request]

jobs:
  build-linux-explorer-glibc-2-29-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build Haven Explorer
      run : |
        mkdir build -p
        cd build
        touch toto
    - name: package haven explorer
      run: |
        cd build/
        tar -czvf haven-linux-explorer-glibc229.tar.gz toto
        echo $PWD
        ls -l
    - uses: actions/upload-artifact@v2
      with:
        name: haven-linux-explorer-glibc229.tar.gz
        path: build/haven-linux-explorer-glibc229.tar.gz
        retention-days: 10
  
  upload-linux-explorer-glibc-2-29-test:
    needs: build-linux-explorer-glibc-2-29-test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: haven-linux-explorer-glibc229.tar.gz
    - name: Upload Haven CLI
      uses: goshiz/do-space-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: 'haven-linux-explorer-glibc229.tar.gz'
        SPACE_NAME: ${{ secrets.SPACE_NAME }}
        SPACE_FOLDER: binaries
        SPACE_REGION: ${{ secrets.SPACE_REGION}}
        SPACE_ACCESS_KEY_ID: ${{ secrets.SPACE_ACCESS_KEY_ID }}
        SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
    - name: notification
      env:
        BINARY_NAME: /haven-linux-explorer-glibc229.tar.gz
        BINARY_URL: https://docs.havenprotocol.org/binaries/
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      shell: bash
      run: |
        export checksum=($(sha256sum haven-linux-explorer-glibc229.tar.gz))
        export payload='{"username": "Github", "content": "Explorer (Linux 2.29) : '${BINARY_URL}${GITHUB_REF##*/}${BINARY_NAME}' (sha256 checksum : '${checksum}')"}'
        echo $payload
        curl -X POST -H "Content-Type: application/json" -d "$payload" $DISCORD_WEBHOOK
      
  publish-linux-explorer-glibc-2-29-test:
    needs: build-linux-explorer-glibc-2-29-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: haven-linux-explorer-glibc229.tar.gz
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: haven-linux-explorer-glibc229.tar.gz
        asset_name: haven-linux-explorer-glibc229.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
        prerelease: true